oracle:
  url: jdbc:oracle:thin:@10.10.50.108:7706:rkpc
  username: cjcl
  password: 11111111
  driverClassName: oracle.jdbc.driver.OracleDriver

phoenix:
  url: jdbc:phoenix:thtfdsj-node4:2181
  driverClassName: org.apache.phoenix.jdbc.PhoenixDriver


import:
  tablename: C2019_000000_SD601_11
  batchsize: 10000


thread:
  core: 5
  max: 8